### PR TITLE
Enable library build

### PR DESCRIPTION
**Pull request by Kokookster**
This PR is a suggestion for a slight refactoring:

* Putting all input structure relevant features into a module file (`input_structure`).
* Add a CMakeLists.txt to build a library.

This would enable a smooth integration into other CMake projects.

### CODE REVIEW

**Comment by glwhart** [comment]
I love what you have done here.!

...I wish Fortran made it easier to set up unit tests so we could make sure nothing has broken. What kind of testing have you done to make sure some corner cases haven't broken?

**Comment by Kokookster** [comment]
Hi! I did not really touch any critical infrastructure ... I think. I just put the structure quantities into one module, so it can be initialized in one call and used from the module. But I also only tested a few cases.

Is there a way to test this by running some scripts and check the output?

**Comment by glwhart** [comment]
Do you think it would be good to add anything to the README about these changes? If so, do you want to add that to your PR? Thanks.

**Comment by Kokookster** [comment]
Yes, I will add something to the README about the library build with CMake.
At the moment, I am struggling with the build in FHI-aims... so the PR is not yet ready.

**Comment by Kokookster** [comment]
Ok, I added something to the README and documented the new routines. This branch is now working in FHI-aims. We also add the citation at the end of every run, when autoGR was used:

```
    For using the generalized regular k-grids created with autoGR, please cite

    Wiley S. Morgan, John E. Christensen, Parker K. Hamilton, Jeremy J. Jorgensen,
    Branton J Campbell, Gus LW Hart, and Rodney W Forcade
    Generalized regular k-point grid generation on the fly

    Comput. Mater. Sci. 173, 109340 (2020)
    https://doi.org/10.1016/j.commatsci.2019.109340

```

**Pull request merged**
